FROM centos:5
MAINTAINER pevma "peter.manev@openinfosecfoundation.org"

RUN yum -y update &&  \
 yum -y install \
 wget git which tar make python \
 gcc-c++ gcc gdb pkgconfig flex bison \
 libtool libpcap-devel pcre-devel zlib-devel \
 file libyaml-devel nss-devel \
 libnet-devel \
 lua-devel GeoIP-devel 

RUN yum -y update &&  \
 yum -y install epel-release 

RUN mkdir -p /opt/QA/results
