FROM fedora:latest
MAINTAINER pevma "peter.manev@openinfosecfoundation.org"

RUN dnf -y update &&  \
 dnf -y install \
 wget tar make which git python coccinelle clang libasan flex bison \
 pkgconfig  gcc-c++ gdb gcc libtool libpcap-devel libcap-ng-devel \
 pcre-devel libyaml-devel file-devel zlib-devel jansson-devel \
 nss-devel libnet-devel libnetfilter_queue-devel \
 lua-devel GeoIP-devel hiredis-devel libnetfilter_log-devel
  
RUN mkdir -p /opt/QA/results

