FROM i386/ubuntu:latest
MAINTAINER pevma "peter.manev@openinfosecfoundation.org"

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get -y upgrade && \
 DEBIAN_FRONTEND=noninteractive apt-get install -y \
 wget curl python git coccinelle clang flex bison  \
 build-essential autoconf automake libtool pkg-config \
 libpcap-dev libcap-ng-dev libnetfilter-queue-dev \
 libpcre3-dev libpcre3 libpcre3-dbg \
 libnet1-dev libyaml-0-2 libyaml-dev zlib1g-dev \
 libmagic-dev liblzma-dev liblzma-dev libnss3-dev libnspr4-dev libjansson-dev \
 libmaxminddb-dev liblz4-dev python3-distutils-extra liblua5.1-0-dev  \
 libhiredis-dev libprelude-dev libnetfilter-log-dev \
 valgrind libdevel-gdb-perl libcapture-tiny-perl \
 wireshark-common python-yaml jq clang-tools \
 libevent-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* 

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
 DEBIAN_FRONTEND=noninteractive apt-get install -y \
 net-tools iputils-ping man-db ethtool \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir -p /opt/QA/results

RUN curl https://sh.rustup.rs -sSf | setarch i386 sh -s -- -y
ENV PATH=/root/.cargo/bin:$PATH
