FROM multiarch/ubuntu-core:ppc64el-xenial
MAINTAINER pevma "peter.manev@openinfosecfoundation.org"

# The following needs to be in place for the docker to be run on 
# Debian/Ubuntu 64 bit machine :
#apt get install -y qemu qemu-user-static qemu-user binfmt-support
#docker run --rm --privileged multiarch/qemu-user-static:register

#if you need to test and try it out that it has been a successful 
# registration :
#docker run -it --rm multiarch/alpine:aarch64-edge /bin/sh

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get -y upgrade && \
 DEBIAN_FRONTEND=noninteractive apt-get install -y \
 wget curl python git coccinelle clang flex bison  \
 build-essential autoconf automake libtool pkg-config \
 libpcap-dev libcap-ng-dev libnetfilter-queue-dev \
 libpcre3-dev libpcre3 libpcre3-dbg \
 libnet1-dev libyaml-0-2 libyaml-dev zlib1g-dev \
 libmagic-dev libnss3-dev libnspr4-dev libjansson-dev \
 libgeoip-dev liblua5.1-0-dev  \
 libhiredis-dev libprelude-dev libnetfilter-log-dev \
 valgrind libdevel-gdb-perl libcapture-tiny-perl \
 wireshark-common python-yaml jq \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* 

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
 DEBIAN_FRONTEND=noninteractive apt-get install -y \
 net-tools iputils-ping man-db ethtool \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir -p /opt/QA/results

# https://forge.rust-lang.org/platform-support.html
#RUN curl https://sh.rustup.rs -sSf | setarch powerpc64le sh -s -- -y
#ENV PATH=/root/.cargo/bin:$PATH
